In [3]:
from jqdatasdk import *
import configparser
 
config = configparser.ConfigParser()
file = 'config.ini'
config.read(file)
user = config.get('login','user')
password = config.get('login','password')
auth(user,password)

auth success （JQData现有流量增加活动，详情请咨询JQData管理员，微信号：JQData02）

# 获取期权数据

**注意**

- 目前只提供期权数据，暂时还不支持期权的回测、模拟及实盘。
- query函数的更多用法详见：[sqlalchemy.orm.query.Query对象](https://docs.sqlalchemy.org/en/rel_1_0/orm/query.html)
- [期权数据获取教程>>>](https://www.joinquant.com/view/community/detail/c0f06b43c15a2f46939cf1239a6274db?type=1)

目前提供的期权数据种类，时间范围及更新频率如下

| 期权数据                   | 时间范围       | 更新频率                     |
| -------------------------- | -------------- | ---------------------------- |
| 期权合约资料               | 上市至今       | 盘后18:00更新                |
| 期权合约调整记录           | 上市至今       | 盘前18:00更新                |
| 期权每日盘前静态文件       | 上市至今       | 盘前9:05日更新               |
| 期权日行情                 | 上市至今       | 盘中实时更新，一分钟更新一次 |
| 期权分钟行情               | 2017-01-01至今 | 盘中实时更新，一分钟更新一次 |
| 股票期权交易和持仓排名统计 | 上市至今       | 盘前8:05更新                 |
| 期权风险指标               | 上市至今       | 盘后19:50更新                |
| 期权行权交收信息           | 上市至今       | 每日10:45更新                |


### 获取期权合约资料

```
from jqdatasdk import *
opt.run_query(query(opt.OPT_CONTRACT_INFO).filter(opt.OPT_CONTRACT_INFO.code==code).limit(n))
```

描述：记录上证50ETF期权，铜期权，白糖期权、豆粕期权自上市以来的所有合约资料，包括合约代码，挂牌日期，开盘参考价等，为回测研究提供最基础的合约信息

**参数：**

- **query(opt.OPT_CONTRACT_INFO)**：表示从opt.OPT_CONTRACT_INFO这张表中查询期权基本资料数据，还可以指定所要查询的字段名，格式如下：query(库名.表名.字段名1，库名.表名.字段名2），多个字段用逗号分隔进行提取；query函数的更多用法详见：[sqlalchemy.orm.query.Query对象](http://docs.sqlalchemy.org/en/rel_1_0/orm/query.html)
- **opt.OPT_CONTRACT_INFO**：收录了期权基本资料数据，表结构和字段信息如下：

**字段设计**

| **名称**            | **类型**      | **描述**                                                     | **示例**                                                     | **备注**                                                     |
| ------------------- | ------------- | ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| code                | str           | 合约代码                                                     | 10001313.XSHG；CU1901C46000.XSGE；SR903C4700.XZCE；M1707-C-2400.XDCE | 注意合约代码使用大写字母                                     |
| trading_code        | str           | 合约交易代码                                                 | 510050C1810M02800                                            | 合约调整会产生新的交易代码                                   |
| name                | str           | 合约简称                                                     | 50ETF购10月2800豆粕购7月2400                                 | 合约调整会产生新的合约简称                                   |
| contract_type       | str           | 合约类型。CO-认购期权，PO-认沽期权                           | CO                                                           |                                                              |
| exchange_code       | str           | 证券市场编码，XSHG：上海证券交易所；XSGE：上海期货交易所；XZCE：郑州商品交易所；XDCE：大连商品交易所 | XSHG                                                         |                                                              |
| currency_id         | str           | 货币代码CNY-人民币                                           | CNY                                                          |                                                              |
| underlying_symbol   | str           | 标的代码                                                     | 510050.XSHG                                                  |                                                              |
| underlying_name     | str           | 标的简称                                                     | 华夏上证50ETF                                                |                                                              |
| underlying_exchange | str           | 标的交易市场                                                 | XSHG                                                         |                                                              |
| underlying_type     | str           | 标的品种类别。ETF-交易型开放式指数基金FUTURE-期货            | ETF                                                          |                                                              |
| exercise_price      | float         | 行权价格                                                     | 2.8                                                          | 合约调整会产生新的行权价格                                   |
| contract_unit       | int           | 合约单位                                                     | 10000                                                        | 合约调整会产生新的合约单位                                   |
| contract_status     | str           | 合约状态：LIST-上市、DELIST-退市。SUSPEND-停牌               | DELIST                                                       | 新期权上市由交易所公布LIST：挂牌日期<=当前日期<=最后交易日DELIST：当前日期>最后交易日 |
| list_date           | str           | 挂牌日期                                                     | 2018-09-25                                                   |                                                              |
| list_reason         | str           | 合约挂牌原因                                                 |                                                              |                                                              |
| list_price          | decimal(20,4) | 开盘参考价                                                   |                                                              | 合约挂牌当天交易所会公布                                     |
| high_limit          | decimal(20,4) | 挂牌涨停价                                                   |                                                              | 合约挂牌当天交易所会公布                                     |
| low_limit           | decimal(20,4) | 挂牌跌停价                                                   |                                                              | 合约上市当天交易所会公布                                     |
| expire_date         | str           | 到期日                                                       | 2018/10/24                                                   |                                                              |
| last_trade_date     | str           | 最后交易日                                                   | 2018/10/24                                                   |                                                              |
| exercise_date       | str           | 行权日                                                       | 2018/10/24                                                   | 50ETF，铜期权是欧式期权，行权日固定。白糖期权和豆粕期权是美式期权，到期日之前都可以行权，行权日不固定，可为空。 |
| delivery_date       | str           | 交收日期                                                     | 2018/10/25                                                   |                                                              |
| is_adjust           | int           | 是否调整                                                     |                                                              | 原合约调整为新的合约会发生合约资料的变化1-是，0-否           |
| delist_date         | str           | 摘牌日期                                                     | 2018/10/24                                                   | 通联数据和交易所有出入,交易所公布的是2018/10/25摘牌日期=最后交易日T+1 |
| delist_reason       | str           | 合约摘牌原因                                                 |                                                              |                                                              |

- **filter(opt.OPT_CONTRACT_INFO.code==code)**：指定筛选条件，通过opt.OPT_CONTRACT_INFO.code==code可以指定你想要查询的合约代码；除此之外，还可以对表中其他字段指定筛选条件；多个筛选条件用英文逗号分隔。
- **limit(n)**：限制返回的数据条数，n指定返回条数。

**返回结果：**

- 返回一个 dataframe，每一行对应数据表中的一条数据， 列索引是您所查询的字段名称

**注意：**

1. **为了防止返回数据量过大, 我们每次最多返回3000行**
2. 不能进行连表查询，即同时查询多张表的数据

**示例：**

In [5]:
opt.run_query(query(opt.OPT_CONTRACT_INFO).filter((opt.OPT_CONTRACT_INFO.underlying_symbol == "510050.XSHG") & (opt.OPT_CONTRACT_INFO.last_trade_date >'2019-05-01'))).head()

,id,code,trading_code,name,contract_type,exchange_code,currency_id,underlying_symbol,underlying_name,underlying_exchange,...,list_price,high_limit,low_limit,expire_date,last_trade_date,exercise_date,delivery_date,is_adjust,delist_date,delist_reason
0,3069,10001501.XSHG,510050C1906A02350,50ETF购6月2303A,CO,XSHG,CNY,510050.XSHG,50ETF,XSHG,...,0.3489,0.6014,0.0964,2019-06-26,2019-06-26,2019-06-26,2019-06-27,1,2019-06-27,合约到期
1,3070,10001502.XSHG,510050C1906A02400,50ETF购6月2352A,CO,XSHG,CNY,510050.XSHG,50ETF,XSHG,...,0.3174,0.5699,0.0649,2019-06-26,2019-06-26,2019-06-26,2019-06-27,1,2019-06-27,合约到期
2,3071,10001503.XSHG,510050C1906A02450,50ETF购6月2401A,CO,XSHG,CNY,510050.XSHG,50ETF,XSHG,...,0.2873,0.5398,0.0348,2019-06-26,2019-06-26,2019-06-26,2019-06-27,1,2019-06-27,合约到期
3,3072,10001504.XSHG,510050C1906A02500,50ETF购6月2450A,CO,XSHG,CNY,510050.XSHG,50ETF,XSHG,...,0.2617,0.5142,0.0092,2019-06-26,2019-06-26,2019-06-26,2019-06-27,1,2019-06-27,合约到期
4,3073,10001505.XSHG,510050C1906A02550,50ETF购6月2500A,CO,XSHG,CNY,510050.XSHG,50ETF,XSHG,...,0.2373,0.4873,0.0001,2019-06-26,2019-06-26,2019-06-26,2019-06-27,1,2019-06-27,合约到期

In [6]:
#查询("10001313.XSHG ")最新的期权基本资料数据。
q=query(opt.OPT_CONTRACT_INFO).filter(opt.OPT_CONTRACT_INFO.code=='10001313.XSHG')
df=opt.run_query(q)
df

,id,code,trading_code,name,contract_type,exchange_code,currency_id,underlying_symbol,underlying_name,underlying_exchange,...,list_price,high_limit,low_limit,expire_date,last_trade_date,exercise_date,delivery_date,is_adjust,delist_date,delist_reason
0,2435,10001313.XSHG,510050C1812A02500,50ETF购12月2450A,CO,XSHG,CNY,510050.XSHG,50ETF,XSHG,...,0.3523,0.6216,0.083,2018-12-26,2018-12-26,2018-12-26,2018-12-27,1,2018-12-27,合约到期

### 获取期权合约调整记录

```
from jqdata  import *
opt.run_query(query(opt.OPT_ADJUSTMENT).filter(opt.OPT_ADJUSTMENT.code==code).limit(n))
```

描述：记录上证50ETF期权因分红除息所带来的期权交易代码，合约简称，合约单位，行权价格的变化

**参数：**

- **query(opt.OPT_ADJUSTMENT)**：表示从opt.OPT_ADJUSTMENT这张表中查询期权合约调整数据，还可以指定所要查询的字段名，格式如下：query(库名.表名.字段名1，库名.表名.字段名2），多个字段用逗号分隔进行提取；query函数的更多用法详见：[sqlalchemy.orm.query.Query对象](http://docs.sqlalchemy.org/en/rel_1_0/orm/query.html)
- **opt.OPT_ADJUSTMENT**：收录了期权合约调整数据，表结构和字段信息如下：

**字段设计**

| **名称**           | **类型** | **描述**                           | **示例**                     | **备注**                        |
| ------------------ | -------- | ---------------------------------- | ---------------------------- | ------------------------------- |
| code               | str      | 合约代码                           | 10001313.XSHG;               |                                 |
| adj_date           | date     | 调整日期                           |                              |                                 |
| contract_type      | str      | 合约类型。CO-认购期权，PO-认沽期权 | CO                           |                                 |
| ex_trading_code    | str      | 原交易代码                         | 510050C1812M02500            | 合约调整会产生新的交易代码      |
| ex_name            | str      | 原合约简称                         | 50ETF购10月2800豆粕购7月2400 | 合约调整会产生新的合约简称      |
| ex_exercise_price  | float    | 原行权价                           |                              |                                 |
| ex_contract_unit   | int      | 原合约单位                         |                              |                                 |
| new_trading_code   | str      | 新交易代码                         | 510050C1812A02500            |                                 |
| new_name           | str      | 新合约简称                         |                              |                                 |
| new_exercise_price | float    | 新行权价                           |                              |                                 |
| new_contract_unit  | int      | 新合约单位                         |                              |                                 |
| adj_reason         | str      | 调整原因                           |                              |                                 |
| expire_date        | str      | 到期日                             | 2018/10/24                   |                                 |
| last_trade_date    | str      | 最后交易日                         | 2018/10/24                   |                                 |
| exercise_date      | str      | 行权日                             | 2018/10/24                   | 50ETF期权是欧式期权，行权日固定 |
| delivery_date      | str      | 交收日期                           | 2018/10/25                   |                                 |
| position           | int      | 合约持仓                           |                              |                                 |

- **filter(opt.OPT_ADJUSTMENT.code==code)**：指定筛选条件，通过opt.OPT_ADJUSTMENT.code==code可以指定你想要查询的合约代码；除此之外，还可以对表中其他字段指定筛选条件；多个筛选条件用英文逗号分隔。
- **limit(n)**：限制返回的数据条数，n指定返回条数。

**返回结果：**

- 返回一个 dataframe，每一行对应数据表中的一条数据， 列索引是您所查询的字段名称

**注意：**

1. **为了防止返回数据量过大, 我们每次最多返回3000行**
2. 不能进行连表查询，即同时查询多张表的数据

**示例：**

In [7]:
#查询("10001313.XSHG ")最新的期权合约调整记录。
q=query(opt.OPT_ADJUSTMENT).filter(opt.OPT_ADJUSTMENT.code=='10001313.XSHG')
df=opt.run_query(q)
df

,id,code,adj_date,contract_type,ex_trading_code,ex_name,ex_exercise_price,ex_contract_unit,new_trading_code,new_name,new_exercise_price,new_contract_unit,adj_reason,expire_date,last_trade_date,exercise_date,delivery_date,position
0,70,10001313.XSHG,2018-12-03,CO,510050C1812M02500,50ETF购12月2500,2.5,10000,510050C1812A02500,50ETF购12月2450A,2.45,10202,除息,2018-12-26,2018-12-26,2018-12-26,2018-12-27,107928

### 获取期权每日盘前静态文件

```
from jqdatasdk import *
opt.run_query(query(opt.OPT_DAILY_PREOPEN).filter(opt.OPT_DAILY_PREOPEN.code==code).limit(n))
```

描述：提供上证50ETF每日交易的基本参数，包含合约单位，行权价格，持仓量，涨跌停价等数据

**参数：**

- **query(opt.OPT_DAILY_PREOPEN)**：表示从opt.OPT_DAILY_PREOPEN这张表中查询期权每日盘前静态数据，还可以指定所要查询的字段名，格式如下：query(库名.表名.字段名1，库名.表名.字段名2），多个字段用逗号分隔进行提取；query函数的更多用法详见：[sqlalchemy.orm.query.Query对象](http://docs.sqlalchemy.org/en/rel_1_0/orm/query.html)
- **opt.OPT_DAILY_PREOPEN**：收录了期权每日盘前静态数据，表结构和字段信息如下：

**字段设计**

| **名称**             | **类型** | **描述**                                                     | **示例**          | **备注**                                                     |
| -------------------- | -------- | ------------------------------------------------------------ | ----------------- | ------------------------------------------------------------ |
| date                 | str      | 交易日期                                                     | 2018-11-09        |                                                              |
| code                 | str      | 合约代码                                                     | 10001313.XSHG     |                                                              |
| trading_code         | str      | 合约交易代码                                                 | 510050C1812M02500 | 保留，每个交易日仍然存在一 一对应关系                        |
| name                 | str      | 合约简称                                                     | 50ETF购12月2500   | 保留，每个交易日仍然存在一 一对应关系                        |
| exchange_code        | str      | 证券市场编码XSHG:上海证券交易所                              | XSHG              |                                                              |
| underlying_symbol    | str      | 标的代码                                                     | 510050.XSHG       |                                                              |
| underlying_name      | str      | 标的名称                                                     | 50ETF             |                                                              |
| underlying_exchange  | str      | 标的交易市场                                                 | XSHG              |                                                              |
| underlying_type      | str      | 标的品种类别，STOCK：股票；ETF：交易型开放式指数基金；FUTURE：期货 | F                 |                                                              |
| exercise_type        | str      | 期权履约方式:A 美式;E 欧式                                   | E                 |                                                              |
| contract_type        | str      | 合约类型。CO-认购期权，PO-认沽期权                           | CO                |                                                              |
| contract_unit        | int      | 合约单位                                                     | 10000             |                                                              |
| exercise_price       | float    | 行权价格                                                     | 2.5               |                                                              |
| list_date            | str      | 挂牌日期                                                     | 2018/4/26         |                                                              |
| last_trade_date      | str      | 最后交易日                                                   | 2018/12/26        |                                                              |
| exercise_date        | str      | 行权日                                                       | 2018/12/26        |                                                              |
| delivery_date        | str      | 交收日期                                                     | 2018/12/27        |                                                              |
| expire_date          | str      | 到期日                                                       | 2018/12/26        |                                                              |
| contract_version     | str      | 合约版本号                                                   | 0                 |                                                              |
| position             | int      | 持仓量                                                       | 13630             |                                                              |
| pre_close            | float    | 前收盘价                                                     | 0.1391            |                                                              |
| pre_settle           | float    | 前结算价                                                     | 0.1391            |                                                              |
| pre_close_underlying | float    | 标的证券前收盘                                               | 2.537             |                                                              |
| is_limit             | str      | 涨跌幅限类型，“N”为有涨跌幅限制                              | N                 |                                                              |
| high_limit           | float    | 涨停价                                                       | 0.3928            |                                                              |
| low_limit            | float    | 跌停价                                                       | 0.0001            |                                                              |
| margin_unit          | float    | 单位保证金                                                   | 4435.4            |                                                              |
| margin_ratio_1       | float    | 保证金计算比例参数一                                         | 12                |                                                              |
| margin_ratio_2       | float    | 保证金计算比例参数二                                         | 7                 |                                                              |
| round_lot            | int      | 整手数                                                       | 1                 |                                                              |
| limit_order_min      | int      | 单笔限价申报下限                                             | 1                 |                                                              |
| limit_order_max      | int      | 单笔限价申报上限                                             | 30                |                                                              |
| market_order_min     | int      | 单笔市价申报下限                                             | 1                 |                                                              |
| marker_order_max     | int      | 单笔市价申报上限                                             | 10                |                                                              |
| quote_change_min     | float    | 最小报价变动(数值)                                           | 0.0001            |                                                              |
| contract_status      | str      | 合约状态信息                                                 | 0000E             | 该字段为8位字符串，左起每位表示特定的含义，无定义则填空格。第1位：‘0’表示可开仓，‘1’表示限制卖出开仓（不.包括备兑开仓）和买入开仓。第2位：‘0’表示未连续停牌，‘1’表示连续停牌。（预留，暂填0）第3位：‘0’表示未临近到期日，‘1’表示距离到期日不足5个交易日。第4位：‘0’表示近期未做调整，‘1’表示最近5个交易日内合约发生过调整。第5位：‘A’表示当日新挂牌的合约，‘E’表示存续的合约 |

- **filter(opt.OPT_DAILY_PREOPEN.code==code)**：指定筛选条件，通过opt.OPT_DAILY_PREOPEN.code==code可以指定你想要查询的合约代码；除此之外，还可以对表中其他字段指定筛选条件；多个筛选条件用英文逗号分隔。
- **limit(n)**：限制返回的数据条数，n指定返回条数。

**返回结果：**

- 返回一个 dataframe，每一行对应数据表中的一条数据， 列索引是您所查询的字段名称

**注意：**

1. **为了防止返回数据量过大, 我们每次最多返回3000行**
2. 不能进行连表查询，即同时查询多张表的数据

**示例：**

In [8]:
#查询("10001313.XSHG ")最新的期权每日盘前静态数据。
q=query(opt.OPT_DAILY_PREOPEN.code,
        opt.OPT_DAILY_PREOPEN.trading_code,
        opt.OPT_DAILY_PREOPEN.name,
opt.OPT_DAILY_PREOPEN.exercise_date,).filter(opt.OPT_DAILY_PREOPEN.code=='10001313.XSHG').order_by(opt.OPT_DAILY_PREOPEN.date.desc()).limit(10)
df=opt.run_query(q)
df

            code       trading_code            name exercise_date
0  10001313.XSHG  510050C1812A02500  50ETF购12月2450A    2018-12-26
1  10001313.XSHG  510050C1812A02500  50ETF购12月2450A    2018-12-26
2  10001313.XSHG  510050C1812A02500  50ETF购12月2450A    2018-12-26
3  10001313.XSHG  510050C1812A02500  50ETF购12月2450A    2018-12-26
4  10001313.XSHG  510050C1812A02500  50ETF购12月2450A    2018-12-26
5  10001313.XSHG  510050C1812A02500  50ETF购12月2450A    2018-12-26
6  10001313.XSHG  510050C1812A02500  50ETF购12月2450A    2018-12-26
7  10001313.XSHG  510050C1812A02500  50ETF购12月2450A    2018-12-26
8  10001313.XSHG  510050C1812A02500  50ETF购12月2450A    2018-12-26
9  10001313.XSHG  510050C1812A02500  50ETF购12月2450A    2018-12-26

### 获取期权日行情数据

```
from jqdatasdk import *
opt.run_query(query(opt.OPT_DAILY_PRICE).filter(opt.OPT_DAILY_PRICE.code==code).limit(n))
```

描述：提供期权每日开盘价，收盘价，最高价，最低价，成交量，成交额，涨跌幅，持仓量等日行情数据

**参数：**

- **query(opt.OPT_DAILY_PRICE)**：表示从opt.OPT_DAILY_PRICE这张表中查询期权日行情数据，还可以指定所要查询的字段名，格式如下：query(库名.表名.字段名1，库名.表名.字段名2），多个字段用逗号分隔进行提取；query函数的更多用法详见：[sqlalchemy.orm.query.Query对象](http://docs.sqlalchemy.org/en/rel_1_0/orm/query.html)
- **opt.OPT_DAILY_PRICE**：收录了期权日行情数据，表结构和字段信息如下：

**字段设计**

| **名称**          | **类型** | **描述**                                                     | **示例**                                                     | **备注**                                                     |
| ----------------- | -------- | ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| code              | str      | 合约代码                                                     | 10001313.XSHG；CU1901C46000.XSGE；SR903C4700.XZCE；M1707-C-2400.XDCE | 合约代码使用大写字母                                         |
| exchange_code     | str      | 证券市场编码，XSHG：上海证券交易所；XSGE：上海期货交易所；XZCE：郑州商品交易所；XDCE：大连商品交易所 | XSHG                                                         |                                                              |
| date              | str      | 交易日期                                                     | 2018/10/25                                                   |                                                              |
| pre_settle        | float    | 前结算价                                                     | 0.1997                                                       |                                                              |
| pre_close         | float    | 前收价                                                       | 0.1997                                                       |                                                              |
| open              | float    | 今开盘                                                       | 0.1683                                                       |                                                              |
| high              | float    | 最高价                                                       | 0.2072                                                       |                                                              |
| low               | float    | 最低价                                                       | 0.1517                                                       |                                                              |
| close             | float    | 收盘价                                                       | 0.2035                                                       |                                                              |
| change_pct_close  | float    | 收盘价涨跌幅(%）                                             |                                                              | 收盘价/前结算价                                              |
| settle_price      | float    | 结算价                                                       | 0.204                                                        | 收盘价是一天交易的最后一个价,它是由于收盘前1分钟所有买卖盘集中撮合而成 ；结算价：原则上，期权合约的结算价格为该合约当日收盘集合竞价的成交价格。但是，如果当日收盘集合竞价未形成成交价格，或者成交价格明显不合理（比如价格倒挂），那么上交所就会考虑期权交易的多重影响因素，另行计算合约的结算价格。即根据同标的、同到期日、同类型其他行权价的期权合约隐含波动率，推算该合约隐含波动率，并以此计算该合约结算价。 |
| change_pct_settle | float    | 结算价涨跌幅(%)                                              |                                                              | 结算价/前结算价                                              |
| volume            | float    | 成交量（张）                                                 | 3126                                                         |                                                              |
| money             | float    | 成交金额（元）                                               | 5620827                                                      |                                                              |
| position          | int      | 持仓量                                                       | 5095                                                         |                                                              |

- **filter(opt.OPT_DAILY_PRICE.code==code)**：指定筛选条件，通过opt.OPT_DAILY_PRICE.code==code可以指定你想要查询的合约代码；除此之外，还可以对表中其他字段指定筛选条件；多个筛选条件用英文逗号分隔。
- **limit(n)**：限制返回的数据条数，n指定返回条数。

**返回结果：**

- 返回一个 dataframe，每一行对应数据表中的一条数据， 列索引是您所查询的字段名称

**注意：**

1. **为了防止返回数据量过大, 我们每次最多返回3000行**
2. 不能进行连表查询，即同时查询多张表的数据

**示例：**

In [9]:
#查询上证50ETF期权（'10001313.XSHG')最近10个交易日的日行情数据。
q=query(opt.OPT_DAILY_PRICE).filter(opt.OPT_DAILY_PRICE.code=='10001313.XSHG').order_by(opt.OPT_DAILY_PRICE.date.desc()).limit(10)
df=opt.run_query(q)
df

,id,code,exchange_code,date,pre_settle,pre_close,open,high,low,close,change_pct_close,settle_price,change_pct_settle,volume,money,position
0,664353,10001313.XSHG,XSHG,2018-12-26,0.0002,0.0001,0.0001,0.0002,0.0001,0.0001,-50.0000,0.0000,-100.0000,1793.0,1881.0,57150
1,663527,10001313.XSHG,XSHG,2018-12-25,0.0005,0.0003,0.0002,0.0005,0.0001,0.0001,-80.0000,0.0002,-60.0000,16065.0,37652.0,58380
2,662687,10001313.XSHG,XSHG,2018-12-24,0.0019,0.0019,0.0011,0.0016,0.0001,0.0003,-84.2105,0.0005,-73.6842,24197.0,210309.0,68717
3,661855,10001313.XSHG,XSHG,2018-12-21,0.0041,0.0040,0.0038,0.0040,0.0017,0.0019,-53.6585,0.0019,-53.6585,28924.0,713756.0,78986
4,330131,10001313.XSHG,XSHG,2018-12-20,0.0071,0.0070,0.0060,0.0076,0.0033,0.0040,-43.6620,0.0041,-42.2535,34494.0,1710959.0,88733
5,329351,10001313.XSHG,XSHG,2018-12-19,0.0132,0.0136,0.0138,0.0153,0.0063,0.0070,-46.9697,0.0071,-46.2121,38833.0,3964228.0,92537
6,328591,10001313.XSHG,XSHG,2018-12-18,0.0253,0.0250,0.0228,0.0258,0.0131,0.0136,-46.2451,0.0132,-47.8261,50645.0,9496665.0,97374
7,327833,10001313.XSHG,XSHG,2018-12-17,0.0264,0.0261,0.0256,0.0286,0.0215,0.0250,-5.3030,0.0253,-4.1667,35123.0,8798706.0,94188
8,327075,10001313.XSHG,XSHG,2018-12-14,0.0408,0.0407,0.0383,0.0383,0.0261,0.0261,-36.0294,0.0264,-35.2941,51335.0,16175427.0,91731
9,326317,10001313.XSHG,XSHG,2018-12-13,0.0307,0.0309,0.0317,0.0472,0.0308,0.0407,32.5733,0.0408,32.8990,74967.0,31073293.0,76893

### 获取期权分钟行情

```
get_price(security, start_date=None, end_date=None, frequency='daily', fields=None, skip_paused=False, count=None)
```

获取期权的历史行情, 按天或者按分钟，这里在使用时注意 end_date 的设置，不要引入未来的数据。

**参数**

- security: 50ETF期权合约代码
- count: **与 start_date 二选一，不可同时使用**. 数量, 返回的结果集的行数, 即表示获取 end_date 之前几个 frequency 的数据
- start_date: **与 count 二选一，不可同时使用**. 字符串或者 [datetime.datetime]/[datetime.date] 对象, 开始时间.
  - 如果 count 和 start_date 参数都没有, 则 start_date 生效, 值是 '2015-01-01'. 注意:
  - 当取分钟数据时, 时间可以精确到分钟, 比如: 传入 `datetime.datetime(2015, 1, 1, 10, 0, 0)` 或者 `'2015-01-01 10:00:00'`.
  - 当取分钟数据时, 如果只传入日期, 则日内时间是当日的 00:00:00.
  - 当取天数据时, 传入的日内时间会被忽略
- end_date: 格式同上, 结束时间, 默认是'2015-12-31', 包含此日期. **注意: 当取分钟数据时, 如果 end_date 只有日期, 则日内时间等同于 00:00:00, 所以返回的数据是不包括 end_date 这一天的**.
- frequency: 单位时间长度, 几天或者几分钟, 现在支持'Xd','Xm', 'daily'(等同于'1d'), 'minute'(等同于'1m'), X是一个正整数, 分别表示X天和X分钟(不论是按天还是按分钟回测都能拿到这两种单位的数据), 注意, 当X > 1时, fields只支持['open', 'close', 'high', 'low', 'volume', 'money']这几个标准字段. 默认值是daily
- fields: 字符串list, 选择要获取的行情数据字段, 默认是None(表示['open', 'close', 'high', 'low', 'volume', 'money']这几个标准字段), 支持SecurityUnitData里面的所有基本属性,，包含：['open', ' close', 'low', 'high', 'volume', 'money', 'factor', 'high_limit',' low_limit', 'avg', ' pre_close', 'paused']
- skip_paused: 是否跳过不交易日期(包括停牌, 未上市或者退市后的日期). 如果不跳过, 停牌时会使用停牌前的数据填充(具体请看SecurityUnitData的paused属性), 上市前或者退市后数据都为 nan, 但要注意:
  - 默认为 False
  - 当 skip_paused 是 True 时, 只能取一只期权的信息 **关于停牌**: 因为此API可以获取多只期权的数据, 可能有的期权停牌有的没有, 为了保持时间轴的一致,我们默认没有跳过停牌的日期, 停牌时使用停牌前的数据填充(请看 SecurityUnitData 的 paused 属性). 如想跳过, 请使用 skip_paused=True 参数, 同时只取一只期权的信息

**返回结果** 返回pandas.DataFrame对象, 行索引是datetime.datetime对象, 列索引是行情字段名字

In [11]:
# 获取10001313.XSHG期权合约的分钟行情
p=get_price('10001313.XSHG','2018-12-21 09:00:00','2018-12-21 12:00:00','1m')
p.head()

                       open   close    high     low  volume     money
2018-12-21 09:31:00  0.0038  0.0034  0.0040  0.0034   310.0  11407.88
2018-12-21 09:32:00  0.0034  0.0032  0.0034  0.0032   169.0   5760.05
2018-12-21 09:33:00  0.0032  0.0033  0.0034  0.0032   228.0   7647.41
2018-12-21 09:34:00  0.0033  0.0031  0.0033  0.0031   446.0  14496.03
2018-12-21 09:35:00  0.0031  0.0031  0.0031  0.0030   340.0  10581.51

### 获取指定时间周期的期权行情

```
get_bars(security, count, unit='1d',
         fields=['date','open','high','low','close'],
         include_now=False, end_dt=None)
```

获取各种时间周期的bar数据，bar的分割方式与主流行情软件相同， 同时还支持返回当前时刻所在 bar 的数据。

**参数**

- security: 期权合约代码
- count: 大于0的整数，表示获取bar的个数。如果行情数据的bar不足count个，返回的长度则小于count个数。
- unit: bar的时间单位, 支持如下周期：'1m', '5m', '15m', '30m', '60m', '120m', '1d', '1w', '1M'。其中m表示分钟，d表示天，w表示周，M表示月。
- fields: 获取数据的字段， 支持如下值：'date', 'open', 'close', 'high', 'low', 'volume', 'money'。
- include_now: 取值True 或者False。 表示是否包含当前bar, 比如策略时间是9:33，unit参数为5m， 如果 include_now=True,则返回9:30-9:33这个分钟 bar。
- end_dt：查询的截止时间，支持的类型为datetime.datetime或None，默认为datetime.now()。

**返回**

返回一个pandas.dataframe对象，可以按任意周期返回期权合约的开盘价、收盘价、最高价、最低价，同时也可以利用date数据查看所返回的数据是什么时刻的。

**示例**

In [10]:
#获取指定时间周期为5m的期权行情数据
df = get_bars('10001313.XSHG',10,'5m',fields=['date','open','high','low','close'],end_dt='2018-12-21 15:00:00')
print(df.head())

                 date    open    high     low   close
0 2018-12-21 14:10:00  0.0019  0.0022  0.0018  0.0021
1 2018-12-21 14:15:00  0.0022  0.0023  0.0019  0.0019
2 2018-12-21 14:20:00  0.0019  0.0022  0.0019  0.0022
3 2018-12-21 14:25:00  0.0022  0.0022  0.0020  0.0020
4 2018-12-21 14:30:00  0.0021  0.0021  0.0020  0.0020

### 获取期权的tick行情

```
get_ticks(security, start_dt, end_dt, count, fields)
```

**期权部分**， 支持 2017-01-01 至今的期权tick数据，提供买五卖五数据。（每0.5秒一次快照）

**购买**：用户如有需要使用tick数据的，可以以走线下商务流程与我们联系，您可以添加管理员微信：**JQData01**，或发送邮件至jqdatasdk@joinquant.com。
**注意**：
（1）目前期权只能获取数据，不能回测及模拟交易；
（2）如果要在聚宽官网回测环境**获取期权数据**，需要申请 Tick级权限，[申请链接](http://joinquant.mikecrm.com/lFNhkfR)

**参数**：

- security: 期货代码
- start_dt: 开始日期
- end_dt: 结束日期
- count: 取出指定时间区间内前多少条的tick数据;
- fields: 选择要获取的行情数据字段，默认为None;
- **期权tick返回结果：**

| 字段名        | 说明           | 字段类型 |
| ------------- | -------------- | -------- |
| time          | 时间           | datetime |
| current       | 当前价         | float    |
| currentvolume | 当前tick成交量 | float    |
| currentmoney  | 当前tick成交额 | float    |
| position      | 持仓量         | float    |
| volume        | 累计成交量     | float    |
| money         | 累计成交额     | float    |
| presettle     | 前结算价       | float    |
| preclose      | 前收价         | float    |
| high          | 当日最高价     | float    |
| low           | 当日最低价     | float    |
| a1_p          | 一档卖价       | float    |
| a1_v          | 一档卖量       | float    |
| …             |                |          |
| a5_p          | 五档卖价       | float    |
| a5_v          | 五档卖量       | float    |
| b1_p          | 一档买价       | float    |
| b1_v          | 一档买量       | float    |
| …             |                |          |
| b5_p          | 五档买价       | float    |
| b5_v          | 五档买量       | float    |

**期权tick数据示例**：

In [13]:
# fields中的字段可以自己添加，下面只是示例
df = get_ticks('10001313.XSHG',start_dt='2018-12-20 09:00:00',end_dt='2018-12-20 10:00:00', fields=['time', 'current', 'volume', 'a1_p', 'b1_p'])
df.head()

                 time  current  volume   a1_p    b1_p
0 2018-12-20 09:25:00    0.006    30.0  0.006  0.0059
1 2018-12-20 09:25:00    0.006    30.0  0.006  0.0059
2 2018-12-20 09:25:20    0.006    30.0  0.006  0.0059
3 2018-12-20 09:25:50    0.006    30.0  0.006  0.0059
4 2018-12-20 09:26:20    0.006    30.0  0.006  0.0059

### 获取股票期权交易和持仓排名统计

```
from jqdatasdk import *
opt.run_query(query(opt.OPT_TRADE_RANK_STK).filter(opt.OPT_TRADE_RANK_STK.underlying_symbol==underlying_symbol).limit(n))
```

描述：统计上证50ETF每日最活跃三个合约的交易排名和持仓量最大三个合约的持仓排名情况

**参数：**

- **query(opt.OPT_TRADE_RANK_STK)**：表示从opt.OPT_TRADE_RANK_STK这张表中查询股票期权交易和持仓排名统计数据，还可以指定所要查询的字段名，格式如下：query(库名.表名.字段名1，库名.表名.字段名2），多个字段用逗号分隔进行提取；query函数的更多用法详见：[sqlalchemy.orm.query.Query对象](http://docs.sqlalchemy.org/en/rel_1_0/orm/query.html)
- **opt.OPT_TRADE_RANK_STK**：收录了股票期权交易和持仓排名统计数据，表结构和字段信息如下：

**字段设计**

| **名称**            | **类型** | **描述**                                                     | **示例**      |
| ------------------- | -------- | ------------------------------------------------------------ | ------------- |
| underlying_symbol   | str      | 标的代码                                                     | 510050.XSHG   |
| underlying_name     | str      | 标的简称                                                     | 华夏上证50ETF |
| underlying_exchange | str      | 证券市场编码：XSHG-上海证券交易所；                          | XSHG          |
| date                | str      | 交易日期                                                     | 2018-10-25    |
| rank                | int      | 排名                                                         | 1             |
| volume              | int      | 数量(张）                                                    | 184891        |
| option_agency       | str      | 期权经营机构                                                 | 华泰证券      |
| rank_type           | str      | 排名统计类型，601001：最活跃三个合约的认购交易排名；601002：最活跃三个合约的认沽交易排名；601003：持仓最大3个合约的认购持仓量排名；601004：持仓最大3个合约的认沽持仓量排名 | 601001        |

- **filter(opt.OPT_TRADE_RANK_STK.underlying_symbol==underlying_symbol)**：指定筛选条件，通过opt.OPT_TRADE_RANK_STK.underlying_symbol==underlying_symbol可以指定你想要查询的标的代码；除此之外，还可以对表中其他字段指定筛选条件；多个筛选条件用英文逗号分隔。
- **limit(n)**：限制返回的数据条数，n指定返回条数。

**返回结果：**

- 返回一个 dataframe，每一行对应数据表中的一条数据， 列索引是您所查询的字段名称

**注意：**

1. **为了防止返回数据量过大, 我们每次最多返回3000行**
2. 不能进行连表查询，即同时查询多张表的数据

**示例：**

In [14]:
#查询最活跃三个合约的认购交易排名（601001）
# from jqdatasdk import *
q=query(opt.OPT_TRADE_RANK_STK).filter(opt.OPT_TRADE_RANK_STK.rank_type==601001).order_by(opt.OPT_TRADE_RANK_STK.date.desc()).limit(10)
df=opt.run_query(q)
df

,id,underlying_symbol,underlying_name,underlying_exchange,date,rank,volume,option_agency,rank_type
0,21679,510050.XSHG,50ETF,XSHG,2019-07-24,3,238258,中信证券,601001
1,21680,510050.XSHG,50ETF,XSHG,2019-07-24,5,199539,海通证券,601001
2,21681,510050.XSHG,50ETF,XSHG,2019-07-24,4,221384,招商证券,601001
3,21682,510050.XSHG,50ETF,XSHG,2019-07-24,2,257391,中泰证券,601001
4,21683,510050.XSHG,50ETF,XSHG,2019-07-24,1,386229,华泰证券,601001
5,21659,510050.XSHG,50ETF,XSHG,2019-07-23,4,137168,中信证券,601001
6,21660,510050.XSHG,50ETF,XSHG,2019-07-23,5,106429,海通证券,601001
7,21661,510050.XSHG,50ETF,XSHG,2019-07-23,2,200699,招商证券,601001
8,21662,510050.XSHG,50ETF,XSHG,2019-07-23,3,171644,中泰证券,601001
9,21663,510050.XSHG,50ETF,XSHG,2019-07-23,1,296752,华泰证券,601001

### 获取期权风险指标数据

```
from jqdatasdk import *
opt.run_query(query(opt.OPT_RISK_INDICATOR).filter(opt.OPT_RISK_INDICATOR.code==code).limit(n))
```

描述：统计各期权合约每日的风险指标，帮助用户更科学的衡量期权合约的价值变动

**参数：**

- **query(opt.OPT_RISK_INDICATOR)**：表示从opt.OPT_RISK_INDICATOR这张表中查询期权风险指标数据，还可以指定所要查询的字段名，格式如下：query(库名.表名.字段名1，库名.表名.字段名2），多个字段用逗号分隔进行提取；query函数的更多用法详见：[sqlalchemy.orm.query.Query对象](http://docs.sqlalchemy.org/en/rel_1_0/orm/query.html)
- **opt.OPT_RISK_INDICATOR**：收录了期权风险指标数据，表结构和字段信息如下：

**字段设计**

| **名称**      | **类型** | **描述**     | **示例**                                                     | **备注**                                        |
| ------------- | -------- | ------------ | ------------------------------------------------------------ | ----------------------------------------------- |
| code          | str      | 合约代码     | 10001313.XSHG；CU1901C46000.XSGE；SR903C4700.XZCE；M1707-C-2400.XDCE | 合约代码使用大写字母                            |
| exchange_code | str      | 证券市场编码 | XSHG                                                         |                                                 |
| date          | str      | 交易日期     | 2018-10-19                                                   |                                                 |
| delta         | float    | DELTA        | 0.906                                                        | **Delta=期权价格变化/期货变化**                 |
| theta         | float    | THETA        | -0.249                                                       | **Theta＝期权价格的变化／距离到期日时间的变化** |
| gamma         | float    | GAMMA        | 0.669                                                        | **Gamma=delta的变化／期货价格的变化**           |
| vega          | float    | VEGA         | 0.138                                                        | **Vega=期权价格变化/波动率的变化**              |
| rho           | float    | RHO          | 0.213                                                        | **Rho=期权价格的变化／无风险利率的变化**        |

- **filter(opt.OPT_RISK_INDICATOR.code==code)**：指定筛选条件，通过opt.OPT_RISK_INDICATOR.code==code可以指定你想要查询的合约代码；除此之外，还可以对表中其他字段指定筛选条件；多个筛选条件用英文逗号分隔。
- **limit(n)**：限制返回的数据条数，n指定返回条数。

**返回结果：**

- 返回一个 dataframe，每一行对应数据表中的一条数据， 列索引是您所查询的字段名称

**注意：**

1. **为了防止返回数据量过大, 我们每次最多返回3000行**
2. 不能进行连表查询，即同时查询多张表的数据

**示例：**

In [15]:
#查询('10001313.XSHG')最新的期权风险指标数据。
# from jqdatasdk import *
q=query(opt.OPT_RISK_INDICATOR).filter(opt.OPT_RISK_INDICATOR.code=='10001313.XSHG').order_by(opt.OPT_RISK_INDICATOR.date.desc()).limit(10)
df=opt.run_query(q)
df

,id,code,exchange_code,date,delta,theta,gamma,vega,rho
0,340957,10001313.XSHG,XSHG,2018-12-25,0.006,-0.191,0.285,0.002,0.000
1,339925,10001313.XSHG,XSHG,2018-12-24,0.019,-0.289,0.689,0.008,0.000
2,334660,10001313.XSHG,XSHG,2018-12-21,0.051,-0.331,1.213,0.028,0.002
3,333630,10001313.XSHG,XSHG,2018-12-20,0.097,-0.464,1.969,0.051,0.004
4,332644,10001313.XSHG,XSHG,2018-12-19,0.162,-0.534,2.995,0.080,0.007
5,331674,10001313.XSHG,XSHG,2018-12-18,0.258,-0.644,3.800,0.114,0.013
6,330726,10001313.XSHG,XSHG,2018-12-17,0.389,-0.753,4.104,0.146,0.023
7,329018,10001313.XSHG,XSHG,2018-12-14,0.403,-0.574,4.174,0.170,0.031
8,328070,10001313.XSHG,XSHG,2018-12-13,0.531,-0.565,4.205,0.184,0.045
9,327122,10001313.XSHG,XSHG,2018-12-12,0.405,-0.570,3.612,0.184,0.036

### 获取期权行权交收信息

```
from jqdatasdk import *
opt.run_query(query(opt.OPT_EXERCISE_INFO).filter(opt.OPT_EXERCISE_INFO.underlying_symbol==underlying_symbol).limit(n))
```

描述：统计上证50ETF期权在各个行权日的交收情况，一定程度上也代表了用户对当前市场的风险偏好

**参数：**

- **query(opt.OPT_EXERCISE_INFO)**：表示从opt.OPT_EXERCISE_INFO这张表中查询期权行权交收信息数据，还可以指定所要查询的字段名，格式如下：query(库名.表名.字段名1，库名.表名.字段名2），多个字段用逗号分隔进行提取；query函数的更多用法详见：[sqlalchemy.orm.query.Query对象](http://docs.sqlalchemy.org/en/rel_1_0/orm/query.html)
- **opt.OPT_EXERCISE_INFO**：收录了期权行权交收信息数据，表结构和字段信息如下：

**字段设计**

| **名称**          | **类型** | **描述**                           | **示例**    | **备注** |      | **优矿对应字段** | **聚源对应字段**         |
| ----------------- | -------- | ---------------------------------- | ----------- | -------- | ---- | ---------------- | ------------------------ |
| underlying_symbol | str      | 标的代码                           | 510050.XSHG |          |      | secID            | ULAInnerCode内部编码转换 |
| underlying_name   | str      | 标的名称                           |             |          |      |                  | ULAName                  |
| exercise_date     | str      | 行权日                             | 2018-10-24  |          |      | exerDate         | ExerciseDate             |
| constract_type    | str      | 合约类型，CO-认购期权，PO-认沽期权 | CO          |          |      | constractType    | ContractType             |
| exercise_number   | int      | 行权数量                           | 12520       |          |      | exerVol          | ExerciseAmt              |

- **filter(opt.OPT_EXERCISE_INFO.underlying_symbol==underlying_symbol)**：指定筛选条件，通过opt.OPT_EXERCISE_INFO.underlying_symbol==underlying_symbol可以指定你想要查询的标的代码；除此之外，还可以对表中其他字段指定筛选条件；多个筛选条件用英文逗号分隔。
- **limit(n)**：限制返回的数据条数，n指定返回条数。

**返回结果：**

- 返回一个 dataframe，每一行对应数据表中的一条数据， 列索引是您所查询的字段名称

**注意：**

1. **为了防止返回数据量过大, 我们每次最多返回3000行**
2. 不能进行连表查询，即同时查询多张表的数据

<!-- **示例：** -->

In [16]:
#查询华夏上证50ETF("510050.XSHG")最新的期权行权交收信息数据。
# from jqdatasdk import *
q=query(opt.OPT_EXERCISE_INFO).filter(opt.OPT_EXERCISE_INFO.underlying_symbol=='510050.XSHG').order_by(opt.OPT_EXERCISE_INFO.exercise_date.desc()).limit(10)
df=opt.run_query(q)
df

,id,underlying_symbol,underlying_name,exercise_date,contract_type,exercise_number
0,102,510050.XSHG,50ETF,2019-07-24,PO,8611
1,101,510050.XSHG,50ETF,2019-07-24,CO,23778
2,100,510050.XSHG,50ETF,2019-06-26,PO,11087
3,99,510050.XSHG,50ETF,2019-06-26,CO,38164
4,98,510050.XSHG,50ETF,2019-05-22,PO,33550
5,97,510050.XSHG,50ETF,2019-05-22,CO,7033
6,96,510050.XSHG,50ETF,2019-04-24,PO,9332
7,95,510050.XSHG,50ETF,2019-04-24,CO,27301
8,94,510050.XSHG,50ETF,2019-03-27,PO,15894
9,93,510050.XSHG,50ETF,2019-03-27,CO,22765

# 期权列表

## 上海交易所

#### 50ETF期权

1.上交所定义：

股票期权合约为上交所统一制定的、规定买方有权在**将来特定时间**以**特定价格**买入或者卖出**约定股票**或者跟踪股票指数的交易型开放式指数基金（ETF）等标的物的标准化合约。

2.合约规格

| 规格               | 详情                                                         |
| ------------------ | ------------------------------------------------------------ |
| 合约标的           | 上证50交易型开放式指数证券投资基金（"50ETF"）                |
| 合约类型           | 认购期权和认沽期权                                           |
| 合约单位           | 10000份                                                      |
| 合约到期月份       | 当月、下月及随后两个季月                                     |
| 行权价格           | 9个（1个平值合约，4个虚值合约，4个实值合约）                 |
| 行权价格间距       | P<=3元，间距为0.05元3<P<=5元，间距为0.1元5<P<=10元，间距为0.25元10<P<=20，间距为0.5元20<P<=50，间距为1元50<P<=100，间距为2.5元100<P，间距为5元 |
| 行权方式           | 到期日行权（欧式期权）                                       |
| 交割方式           | 实物交割（业务规则另有规定的除外）                           |
| 到期日             | 到期月份的第四个星期三（遇法定节假日顺延）                   |
| 行权日             | 同合同到期日，行权指令提交时间为9:15-9:25,9:30-11:30,13:00-15:30 |
| 交收日             | 行权日次一交易日                                             |
| 交易时间           | 上午9:15-9:25，9:30-11:30（9:15-9:25为开盘集合竞价时间）下午13:00-15:00（14:57-15:00为收盘集合竞价时间） |
| 委托类型           | 普通现价委托市价剩余转限价委托市价剩余撤销委托全额即时限价委托全额即时市价委托业务规则规定的其他委托类型 |
| 买卖类型           | 买入开仓买入平仓卖出开仓卖出平仓备兑开仓备兑平仓业务规则规定的其他买卖类型 |
| 最小报价单位       | 0.0001元                                                     |
| 申报单位           | 1张或其整数倍                                                |
| 涨跌幅限制         | 认购期权最大涨幅=max｛合约标的前收盘价×0.5%，min [（2×合约标的前收盘价－行权价格），合约标的前收盘价]×10％｝认购期权最大跌幅=合约标的前收盘价×10％认沽期权最大涨幅=max｛行权价格×0.5%，min [（2×行权价格－合约标的前收盘价），合约标的前收盘价]×10％｝认沽期权最大跌幅=合约标的前收盘价×10％ |
| 熔断机制           | 连续竞价期间，期权合约盘中交易价格较最近参考价格涨跌幅度达到或者超过50%且价格涨跌幅绝对值达到或者超过5个最小报价单位时，期权合约进入3分钟的集合竞价交易阶段。 |
| 开仓保证金最低标准 | 认购期权义务仓开仓保证金=[合约前结算价+Max(12%*合约标的前收盘价-认购期权虚值，7%*合约标的前收盘价) ]*合约单位认沽期权义务仓开仓保证金=Min[合约前结算价+Max(12%*合约标的前收盘价-认沽期权虚值，7%*行权价格），行权价格] * 合约单位 |
| 维持保证金最低标准 | 认购期权义务仓维持保证金=[合约结算价+Max（12%×合约标的收盘价-认购期权虚值，7%×合约标的收盘价）] × 合约单位认沽期权义务仓维持保证金=Min[合约结算价 +Max（12%×合标的收盘价-认沽期权虚值，7%×行权价格），行权价格] × 合约单位 |

## 上海期货交易所

#### 铜期权

| 规格         | 详情                                                         |
| ------------ | ------------------------------------------------------------ |
| 合约标的物   | 阴极铜期货合约（5吨）                                        |
| 合约类型     | 看涨期权，看跌期权                                           |
| 交易单位     | 1手阴极铜期货合约                                            |
| 报价单位     | 元（人民币）/吨                                              |
| 最小变动价位 | 1 元/吨                                                      |
| 涨跌停板幅度 | 与阴极铜期货合约涨跌停板幅度相同                             |
| 合约月份     | 与上市标的期货合约相同                                       |
| 交易时间     | 上午9:00-11:30下午13:30-15:00及交易所规定的其他时间          |
| 最后交易日   | 标的期货合约交割月前第一月的倒数第五个交易日，交易所可以根据国家法定节假日调整最后交易日 |
| 到期日       | 同最后交易日                                                 |
| 行权价格     | 行权价格覆盖阴极铜期货合约上一交易日结算价上下1倍当日涨跌停板幅度对应的价格范围。行权价格≤40000元/吨，行权价格间距为500元/吨；40000元/吨＜行权价格≤80000元/吨，行权价格间距为1000元/吨；行权价格＞80000元/吨，行权价格间距为2000元/吨 |
| 行权方式     | 欧式。到期日买方可以在15:30之前提出行权申请、放弃申请        |
| 交易代码     | 看涨期权：CU-合约月份-C-行权价格看跌期权：CU-合约月份-P-行权价格 |
| 上市交易所   | 上海期货交易所                                               |

#### 天然橡胶期权

| 规格         | 详情                                                         |
| ------------ | ------------------------------------------------------------ |
| 合约标的物   | 天然橡胶期货合约（10吨）                                     |
| 合约类型     | 看涨期权，看跌期权                                           |
| 交易单位     | 1手天然橡胶期货合约                                          |
| 报价单位     | 元（人民币）/吨                                              |
| 最小变动价位 | 1元/吨                                                       |
| 涨跌停板幅度 | 与天然橡胶期货合约涨跌停板幅度相同                           |
| 合约月份     | 与上市标的期货合约相同                                       |
| 交易时间     | 上午9:00-11:30下午13:30-15:00及交易所规定的其他时间          |
| 最后交易日   | 标的期货合约交割月前一个月的倒数第五个交易日，交易所可以根据国家法定节假日等调整最后交易日 |
| 到期日       | 同最后交易日                                                 |
| 行权价格     | 行权价格覆盖天然橡胶期货合约上一交易日结算价上下浮动1.5倍当日涨跌停板幅度对应的价格范围。行权价格≤10000元/吨，行权价格间距为100元/吨；10000元/吨＜行权价格≤25000元/吨，行权价格间距为250元/吨；行权价格＞25000元/吨，行权价格间距为500元/吨 |
| 行权方式     | 美式。买方可在到期日前任一交易日的交易时间提交行权申请；买方可在到期日15:30之前提交行权申请、放弃申请 |
| 交易代码     | 看涨期权：RU-合约月份-C-行权价格 看跌期权：RU-合约月份-P-行权价格 |
| 上市交易所   | 上海期货交易所                                               |

## 郑州商品交易所

#### 白糖期权

**白糖期权合约( 白糖期货1909合约前执行本合约)**

| 规格         | 详情                                                         |
| ------------ | ------------------------------------------------------------ |
| 合约标的物   | 白糖期货合约                                                 |
| 合约类型     | 看涨期权、看跌期权                                           |
| 交易单位     | 1手（10吨）白糖期货合约                                      |
| 报价单位     | 元（人民币）/吨                                              |
| 最小变动价位 | 0.5元/吨                                                     |
| 涨跌停板幅度 | 与白糖期货合约涨跌停板幅度相同                               |
| 合约月份     | 1、3、5、7、9、11月                                          |
| 交易时间     | 每周一至周五上午9:00—11:30，下午13:30—15:00，以及交易所规定的其他交易时间 |
| 最后交易日   | 标的期货合约交割月份前二个月的倒数第5个交易日，以及交易所规定的其他日期 |
| 到期日       | 同最后交易日                                                 |
| 行权价格     | 以白糖期货前一交易日结算价为基准，按行权价格间距挂出5个实值期权、1个平值期权和5个虚值期权。行权价格≤3000元/吨，行权价格间距为50元/吨；3000元/吨＜行权价格≤10000元/吨，行权价格间距为100元/吨；行权价格＞10000元/吨，行权价格间距为200元/吨 |
| 行权方式     | 美式。买方可在到期日前任一交易日的交易时间提交行权申请；买方可在到期日15:30之前提交行权申请、放弃申请 |
| 交易代码     | 看涨期权：SR—合约月份—C—行权价格看跌期权：SR—合约月份—P—行权价格 |
| 上市交易所   | 郑州商品交易所                                               |

**白糖期权合约 (白糖期货1909及其后合约执行本合约)**

| 规格         | 详情                                                         |
| ------------ | ------------------------------------------------------------ |
| 合约标的物   | 白糖期货合约                                                 |
| 合约类型     | 看涨期权、看跌期权                                           |
| 交易单位     | 1手（10吨）白糖期货合约                                      |
| 报价单位     | 元（人民币）/吨                                              |
| 最小变动价位 | 0.5元/吨                                                     |
| 涨跌停板幅度 | 与白糖期货合约涨跌停板幅度相同                               |
| 合约月份     | 标的期货合约中的连续两个近月，其后月份在标的期货合约结算后持仓量达到5000手（双边）之后的第二个交易日挂牌 |
| 交易时间     | 每周一至周五上午9:00—11:30，下午13:30—15:00，以及交易所规定的其他交易时间 |
| 最后交易日   | 标的期货合约交割月份前一个月的第3个交易日，以及交易所规定的其他日期 |
| 到期日       | 同最后交易日                                                 |
| 行权价格     | 以白糖期货前一交易日结算价为基准，按行权价格间距挂出5个实值期权、1个平值期权和5个虚值期权。行权价格≤3000元/吨，行权价格间距为50元/吨；3000元/吨＜行权价格≤10000元/吨，行权价格间距为100元/吨；行权价格＞10000元/吨，行权价格间距为200元/吨 |
| 行权方式     | 美式。买方可在到期日前任一交易日的交易时间提交行权申请；买方可在到期日15:30之前提交行权申请、放弃申请 |
| 交易代码     | 看涨期权：SR—合约月份—C—行权价格看跌期权：SR—合约月份—P—行权价格 |
| 上市交易所   | 郑州商品交易所                                               |

#### 棉花期权

| 规格         | 详情                                                         |
| ------------ | ------------------------------------------------------------ |
| 合约标的物   | 一号棉花期货合约                                             |
| 合约类型     | 看涨期权、看跌期权                                           |
| 交易单位     | 1手一号棉花期货合约                                          |
| 报价单位     | 元（人民币）/吨                                              |
| 最小变动价位 | 1元/吨                                                       |
| 涨跌停板幅度 | 与棉花期货合约涨跌停板幅度相同                               |
| 合约月份     | 标的期货合约中的连续两个近月，其后月份在标的期货合约结算后持仓量达到5000手（双边）之后的第二个交易日挂牌 |
| 交易时间     | 每周一至周五上午9:00-11:30，下午13:30-15:00，以及交易所规定的其他交易时间 |
| 最后交易日   | 标的期货合约交割月份前一个月的第3个交易日，以及交易所规定的其他日期 |
| 到期日       | 同最后交易日                                                 |
| 行权价格     | 以棉花期货前一交易日结算价为基准，按行权价格间距挂出6个实值期权、1个平值期权和6个虚值期权。行权价格≤10000元/吨，行权价格间距为100元/吨；10000元/吨＜行权价格≤20000元/吨，行权价格间距为200元/吨；行权价格＞20000元/吨，行权价格间距为400元/吨 |
| 行权方式     | 美式。买方可在到期日前任一交易日的交易时间提交行权申请；买方可在到期日15:30之前提交行权申请、放弃申请 |
| 交易代码     | 看涨期权：CF-合约月份-C-行权价格 看跌期权：CF-合约月份-P-行权价格 |
| 上市交易所   | 郑州商品交易所                                               |

# 大连商品交易所

#### 豆粕期权

| 规格         | 详情                                                         |
| ------------ | ------------------------------------------------------------ |
| 合约标的物   | 豆粕期货合约                                                 |
| 合约类型     | 看涨期权、看跌期权                                           |
| 交易单位     | 1手（10吨）豆粕期货合约                                      |
| 报价单位     | 元（人民币）/吨                                              |
| 最小变动价位 | 0.5元/吨                                                     |
| 涨跌停板幅度 | 与豆粕期货合约涨跌停板幅度相同                               |
| 合约月份     | 1、3、5、7、8、9、11、12月                                   |
| 交易时间     | 每周一至周五上午9:00～11:30，下午13:30～15:00， 以及交易所规定的其他时间 |
| 最后交易日   | 标的期货合约交割月份前一个月的第5个交易日                    |
| 到期日       | 同最后交易日                                                 |
| 行权价格     | 行权价格覆盖豆粕期货合约上一交易日结算价上下浮动1.5倍当日涨跌停板幅度对应的价格范围。行权价格 ≤2000元/吨，行权价格间距为25元/吨；2000元/吨<行 权价格≤5000元/吨，行权价格间距为50元/吨； 行权 价格＞5000元/吨， 行权价格间距为100元/吨。 |
| 行权方式     | 美式。买方可以在到期日之前任一交易日的交易时 间，以及到期日15:30之前提出行权申请。 |
| 交易代码     | 看涨期权：M-合约月份-C-行权价格 看跌期权：M-合约月份-P-行权价格 |
| 上市交易所   | 大连商品交易所                                               |

#### 玉米期权

| 规格         | 详情                                                         |
| ------------ | ------------------------------------------------------------ |
| 合约标的物   | 玉米期货合约                                                 |
| 合约类型     | 看涨期权、看跌期权                                           |
| 交易单位     | 1手（10吨）玉米期货合约                                      |
| 报价单位     | 元（人民币）/吨                                              |
| 最小变动价位 | 0.5元/吨                                                     |
| 涨跌停板幅度 | 与玉米期货合约涨跌停板幅度相同                               |
| 合约月份     | 1、 3、 5、 7、 9、 11月                                     |
| 交易时间     | 每周一至周五上午9:00-11:30，下午13:30-15:00，以及交易所规定的其他交易时间 |
| 最后交易日   | 标的期货合约交割月份前一个月的第5个交易日                    |
| 到期日       | 同最后交易日                                                 |
| 行权价格     | 行权价格范围覆盖玉米期货合约上一交易日结算价上下浮动1.5倍当日涨跌停板幅度对应的价格范围。行权价格≤1000元/吨，行权价格间距为10元/吨；1000元/吨<行权价格≤3000元/吨，行权价格间距为20元/吨；行权价格>3000元/吨，行权价格间距为40元/吨。 |
| 行权方式     | 美式。买方可在到期日前任一交易日的交易时间，以及到期日15:30之前提出行权申请。 |
| 交易代码     | 看涨期权：C-合约月份-C-行权价格 看跌期权：C-合约月份-P-行权价格 |
| 上市交易所   | 大连商品交易所                                               |